
package proyecto_final_grupo2;


import Conexion.conexion;
import java.sql.SQLException;
import java.sql.*;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ELIMINAR extends javax.swing.JFrame {
    conexion con = new conexion();
    Connection cn = con.conectar();
    PreparedStatement ps;
    ResultSet rs;
   
  
    
    public void limpiar(){
        txtbuscartodo.setText("");
    }
  
            
    
    public ELIMINAR() {
        initComponents();
        setLocationRelativeTo(null);
        Mostrar("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbuscartodo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ELIMINAR AUTO DEL LISTADO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. Placa:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        txtbuscartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscartodoActionPerformed(evt);
            }
        });
        txtbuscartodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscartodoKeyPressed(evt);
            }
        });
        jPanel2.add(txtbuscartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 120, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Propietario", "No. Placa", "Tipo de Vehiculo", "Hora de Entrada"
            }
        ));
        Tabla.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                TablaAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 480, 160));

        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btneliminar.setText("ELIMINAR AUTO");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel2.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/53b2ddd96c334e8cd52202670476e653 (2).jpg"))); // NOI18N
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new MENU().toFront();
        new MENU().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TablaAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaAncestorMoved

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
    Borrar();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String campo = txtbuscartodo.getText();
        String where = "";

        if(!"".equals(campo))
        {
            where = "WHERE Placa = '"+ campo + "'";
        }
        try{
            DefaultTableModel modelo=new DefaultTableModel();
            Tabla.setModel(modelo);
            String sql = "SELECT Propietario, Placa, Tipo_Vehiculo,Hora_Entrada FROM parqueo " + where;

            System.out.println(sql);

            ps =cn.prepareStatement(sql);
            rs =ps.executeQuery();
            ResultSetMetaData rsMd= rs.getMetaData();
            int cantidadColumnas =rsMd.getColumnCount();
            modelo.addColumn("Propietario");
            modelo.addColumn("No. Placa");
            modelo.addColumn("Tip de Vehiculo");
            modelo.addColumn("Hora de Entrada");
            while(rs.next()){
                Object [] filas = new Object[cantidadColumnas];
                for(int i = 0; i< cantidadColumnas; i++){
                    filas [i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
        }catch(SQLException ex){
            System.err.println(ex.toString());

        }
    }//GEN-LAST:event_buscarActionPerformed

    private void txtbuscartodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscartodoKeyPressed

    }//GEN-LAST:event_txtbuscartodoKeyPressed

    private void txtbuscartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscartodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscartodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ELIMINAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ELIMINAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ELIMINAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ELIMINAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ELIMINAR().setVisible(true);
            }
        });
    }
 void Mostrar(){
    try{
            DefaultTableModel modelo=new DefaultTableModel();
            Tabla.setModel(modelo);
           
            String sql = "SELECT Propietario, Placa, Tipo_Vehiculo,Hora_Entrada FROM parqueo ";

            System.out.println(sql);

            ps =cn.prepareStatement(sql);
            rs =ps.executeQuery();
            ResultSetMetaData rsMd= rs.getMetaData();
            int cantidadColumnas =rsMd.getColumnCount();
            modelo.addColumn("Propietario");
            modelo.addColumn("No. Placa");
            modelo.addColumn("Tip de Vehiculo");
            modelo.addColumn("Hora de Entrada");
            while(rs.next()){
                Object [] filas = new Object[cantidadColumnas];
                for(int i = 0; i< cantidadColumnas; i++){
                    filas [i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
        }catch(SQLException ex){
            System.err.println(ex.toString());

        }
 } 

public void Mostrar(String Propietario){
    DefaultTableModel modelo=new DefaultTableModel();
    modelo.addColumn("Propietario");
    modelo.addColumn("No. Placa");
    modelo.addColumn("Tipo de Vehiculo");    
    modelo.addColumn("Hora de Entrada");
    Tabla.setModel(modelo);
    String sql="";
    if(Propietario.equals("")){
        sql="Select*from parqueo";
    }else{
        sql="Select*from parqueo where Nombre like'%"+Propietario+"%'";
    }
    String parqueo[]=new String[4];
    Statement set;
    try {
        set = cn.createStatement(); 
        ResultSet resul=set.executeQuery(sql);
        while(resul.next()){
            parqueo[0]=resul.getString(1);
              parqueo[1]=resul.getString(2);
                parqueo[2]=resul.getString(3);  
                parqueo[3]=resul.getString(4);
                  modelo.addRow(parqueo);
                  
                
        }
        Tabla.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(ELIMINAR.class.getName()).log(Level.SEVERE, null, ex);
    }
   
    
}
 
public void Borrar(){
    int fila=Tabla.getSelectedRow();
    String Placa=Tabla.getValueAt(fila,1).toString();
    int n=JOptionPane.showConfirmDialog(null,"Desea eliminar registro","ELIMINAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
    if(n==JOptionPane.YES_NO_OPTION){
    try {
        PreparedStatement borrar=cn.prepareStatement("Delete from parqueo where Placa='"+Placa+"'");
        borrar.executeUpdate();
        Mostrar("");
    } catch (SQLException ex) {
        Logger.getLogger(ELIMINAR.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
}
           
       
 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Tabla;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbuscartodo;
    // End of variables declaration//GEN-END:variables
}
